# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maximegaudin/Documents/Personnel/Developpement/C++/PropositionLogic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maximegaudin/Documents/Personnel/Developpement/C++/PropositionLogic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maximegaudin/Documents/Personnel/Developpement/C++/PropositionLogic/CMakeFiles /Users/maximegaudin/Documents/Personnel/Developpement/C++/PropositionLogic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maximegaudin/Documents/Personnel/Developpement/C++/PropositionLogic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lp

# Build rule for target.
lp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lp
.PHONY : lp

# fast build rule for target.
lp/fast:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/build
.PHONY : lp/fast

src/CNFConverter.o: src/CNFConverter.cc.o
.PHONY : src/CNFConverter.o

# target to build an object file
src/CNFConverter.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/CNFConverter.cc.o
.PHONY : src/CNFConverter.cc.o

src/CNFConverter.i: src/CNFConverter.cc.i
.PHONY : src/CNFConverter.i

# target to preprocess a source file
src/CNFConverter.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/CNFConverter.cc.i
.PHONY : src/CNFConverter.cc.i

src/CNFConverter.s: src/CNFConverter.cc.s
.PHONY : src/CNFConverter.s

# target to generate assembly for a file
src/CNFConverter.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/CNFConverter.cc.s
.PHONY : src/CNFConverter.cc.s

src/NNFConverter.o: src/NNFConverter.cc.o
.PHONY : src/NNFConverter.o

# target to build an object file
src/NNFConverter.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/NNFConverter.cc.o
.PHONY : src/NNFConverter.cc.o

src/NNFConverter.i: src/NNFConverter.cc.i
.PHONY : src/NNFConverter.i

# target to preprocess a source file
src/NNFConverter.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/NNFConverter.cc.i
.PHONY : src/NNFConverter.cc.i

src/NNFConverter.s: src/NNFConverter.cc.s
.PHONY : src/NNFConverter.s

# target to generate assembly for a file
src/NNFConverter.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/NNFConverter.cc.s
.PHONY : src/NNFConverter.cc.s

src/Node.o: src/Node.cc.o
.PHONY : src/Node.o

# target to build an object file
src/Node.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/Node.cc.o
.PHONY : src/Node.cc.o

src/Node.i: src/Node.cc.i
.PHONY : src/Node.i

# target to preprocess a source file
src/Node.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/Node.cc.i
.PHONY : src/Node.cc.i

src/Node.s: src/Node.cc.s
.PHONY : src/Node.s

# target to generate assembly for a file
src/Node.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/Node.cc.s
.PHONY : src/Node.cc.s

src/dot.o: src/dot.cc.o
.PHONY : src/dot.o

# target to build an object file
src/dot.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/dot.cc.o
.PHONY : src/dot.cc.o

src/dot.i: src/dot.cc.i
.PHONY : src/dot.i

# target to preprocess a source file
src/dot.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/dot.cc.i
.PHONY : src/dot.cc.i

src/dot.s: src/dot.cc.s
.PHONY : src/dot.s

# target to generate assembly for a file
src/dot.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/dot.cc.s
.PHONY : src/dot.cc.s

src/lexer.o: src/lexer.cc.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/lexer.cc.o
.PHONY : src/lexer.cc.o

src/lexer.i: src/lexer.cc.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/lexer.cc.i
.PHONY : src/lexer.cc.i

src/lexer.s: src/lexer.cc.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/lexer.cc.s
.PHONY : src/lexer.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/parser.o: src/parser.cc.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cc.o:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/parser.cc.o
.PHONY : src/parser.cc.o

src/parser.i: src/parser.cc.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cc.i:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/parser.cc.i
.PHONY : src/parser.cc.i

src/parser.s: src/parser.cc.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cc.s:
	$(MAKE) -f CMakeFiles/lp.dir/build.make CMakeFiles/lp.dir/src/parser.cc.s
.PHONY : src/parser.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... lp"
	@echo "... rebuild_cache"
	@echo "... src/CNFConverter.o"
	@echo "... src/CNFConverter.i"
	@echo "... src/CNFConverter.s"
	@echo "... src/NNFConverter.o"
	@echo "... src/NNFConverter.i"
	@echo "... src/NNFConverter.s"
	@echo "... src/Node.o"
	@echo "... src/Node.i"
	@echo "... src/Node.s"
	@echo "... src/dot.o"
	@echo "... src/dot.i"
	@echo "... src/dot.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

